name = "Transformers"
uuid = "21ca0261-441d-5938-ace7-c90938fde4d4"
authors = ["chengchingwen <adgjl5645@hotmail.com>"]
version = "0.2.8"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BytePairEncoding = "a4280ba5-8788-555a-8ca8-4a8c3d966a71"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DoubleArrayTries = "abbaa0e5-f788-499c-92af-c35ff4258c82"
Fetch = "bb354801-46f6-40b6-9c3d-d42d7a74c775"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FuncPipelines = "9ed96fbb-10b6-44d4-99a6-7e2a3dc8861b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NNlibCUDA = "a00861dc-f156-4864-bf3c-e6376f28a68d"
NeuralAttentionlib = "12afc1b8-fad6-47e1-9132-84abc478905f"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrimitiveOneHot = "13d12f88-f12b-451e-9b9f-13b97e01cc85"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
StructWalk = "31cdf514-beb7-4750-89db-dda9d2eb8d3d"
TextEncodeBase = "f92c20c0-9f2a-4705-8116-881385faba05"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
ValSplit = "0625e100-946b-11ec-09cd-6328dd093154"
WordTokenizers = "796a5d58-b03d-544a-977e-18100b691f6e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BytePairEncoding = "0.4"
CUDA = "3.10, 4, 5"
ChainRulesCore = "1.15"
DataDeps = "0.7"
DataStructures = "0.18"
DoubleArrayTries = "0.1"
Fetch = "0.1.3"
FillArrays = "0.13, 1"
Flux = "0.13.4"
FuncPipelines = "0.2.3"
Functors = "0.2, 0.3, 0.4"
HTTP = "0.9, 1"
HuggingFaceApi = "0.1"
JSON3 = "1.12"
LRUCache = "1.5"
LightXML = "0.9"
NNlib = "0.8"
NNlibCUDA = "0.2"
NeuralAttentionlib = "0.2.12"
Pickle = "0.3"
PrimitiveOneHot = "0.1, 0.2"
Static = "0.7, 0.8"
StringViews = "1"
StructWalk = "0.2"
TextEncodeBase = "0.7"
ValSplit = "0.1"
WordTokenizers = "0.5.6"
Zygote = "0.6.59"
julia = "1.6"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[targets]
test = ["Test", "Logging", "ZipFile", "ChainRulesTestUtils"]
