name = "Transformers"
uuid = "21ca0261-441d-5938-ace7-c90938fde4d4"
authors = ["chengchingwen <adgjl5645@hotmail.com>"]
version = "0.1.15"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BytePairEncoding = "a4280ba5-8788-555a-8ca8-4a8c3d966a71"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Fetch = "bb354801-46f6-40b6-9c3d-d42d7a74c775"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NNlibCUDA = "a00861dc-f156-4864-bf3c-e6376f28a68d"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrimitiveOneHot = "13d12f88-f12b-451e-9b9f-13b97e01cc85"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
WordTokenizers = "796a5d58-b03d-544a-977e-18100b691f6e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
AbstractTrees = "0.3"
Adapt = "3.3"
BSON = "0.3.4"
BytePairEncoding = "0.2"
CUDA = "3.8"
ChainRulesCore = "1.11"
DataDeps = "0.7"
DataStructures = "0.18"
Fetch = "0.1.3"
Flux = "0.12"
Functors = "0.2"
HTTP = "0.9"
InternedStrings = "0.7"
JSON = "0.21"
LightXML = "0.9"
MacroTools = "0.5"
NNlib = "0.8"
NNlibCUDA = "0.2"
Pickle = "0.3"
PrimitiveOneHot = "0.1"
Requires = "1"
WordTokenizers = "0.5.6"
ZipFile = "0.9"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
