[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TextEncodeBase = "f92c20c0-9f2a-4705-8116-881385faba05"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Transformers = "21ca0261-441d-5938-ace7-c90938fde4d4"
